### ISSUE TITLE
Unable to complete habit

### ISSUE THREAD

**Issue by Saitekku** [sitek94/habit-tracker-app#40]
It's already 00:30 and I can't mark habit as completed. 

![Hour](https://user-images.githubusercontent.com/26302690/101999142-5fa33280-3cda-11eb-96e6-82f2f992421e.PNG)

**Comment by sitek94** [comment]
Dobra wiem juz o co chodzi. Bo zrobilem poki co dwa w jednym - strefa
czasowa +  jezyk. Wiec jak zmieniasz na US to zmienia sie tez godzina, wiec
teoretycznie jestes w stanach a tam jeszcze nie ma niedzieli

**Comment by sitek94** [comment]
a jak ogolnie apka? pomijajac jakies bugi ewentualne

**Comment by sitek94** [comment]
Hi, thank you for spotting this! 🥇 

The problem was with the way a new date was created. 

In the database the dates are stored as strings in `YYYY-MM-DD` format and when I needed to use a date object I would create one like so:
```js
new Date('2020-12-15');
```
What I didn't know when then is that this is actually unstable and not recommended way of parsing a date string. As per MDN:
>Parsing of date strings with the Date constructor (and Date.parse(), which works the same way) is strongly discouraged due to browser differences and inconsistencies.

These inconsistencies are what was causing the problem:
```js
// Dash separator
new Date('2020-12-15');
// → Sun Dec 13 2020 01:00:00 GMT+0100 ...

// Slash separator
new Date('2020/12/15');
// → Sun Dec 13 2020 00:00:00 GMT+0100 ...
``` 

I'm now using `parseISO` from `date-fns` to parse a date string so it should fix it.

Also, I'm going to enable changing the state of future checkmarks just in case someone is 100% sure that they going to perform a habit 👌
